package com.apptolast.invernaderos.features.notification

import io.hypersistence.utils.hibernate.id.Tsid
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Table
import org.hibernate.annotations.JdbcTypeCode
import org.hibernate.type.SqlTypes
import java.time.Instant

/**
 * JPA entity for metadata.notification_log.
 *
 * Append-only audit record of every notification dispatch attempt.
 * [id] is generated by the DB TSID function (assigned at INSERT; null before save).
 * [payloadJson] is persisted as JSONB via @JdbcTypeCode(SqlTypes.JSON).
 * [status] is a plain String (CHECK constraint enforced in SQL); the domain layer
 *   converts to/from [com.apptolast.invernaderos.features.notification.domain.model.NotificationStatus].
 * [notificationType] is a plain String; the domain layer converts to/from
 *   [com.apptolast.invernaderos.features.notification.domain.model.NotificationType].
 *
 * Equals/hashCode are based on [id] (TSID), consistent with AlertStateChange pattern.
 */
@Entity
@Table(name = "notification_log", schema = "metadata")
class NotificationLogEntity(
    @Id
    @Tsid
    var id: Long? = null,

    @Column(name = "tenant_id", nullable = false)
    val tenantId: Long,

    @Column(name = "user_id", nullable = false)
    val userId: Long,

    @Column(name = "device_token_id")
    val deviceTokenId: Long? = null,

    @Column(name = "notification_type", nullable = false, length = 32)
    val notificationType: String,

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "payload_json", nullable = false, columnDefinition = "JSONB")
    val payloadJson: String,

    @Column(name = "status", nullable = false, length = 32)
    var status: String,

    @Column(name = "fcm_message_id", length = 128)
    var fcmMessageId: String? = null,

    @Column(name = "error")
    var error: String? = null,

    @Column(name = "sent_at", nullable = false)
    val sentAt: Instant = Instant.now()
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is NotificationLogEntity) return false
        return id != null && id == other.id
    }

    override fun hashCode(): Int = id?.hashCode() ?: 0
}
